### ISSUE TITLE
Why do you need installing docker-compose ?

### ISSUE THREAD

**Issue by dlgiang** [ajeetraina/jmeter-docker#3]
Just ask because i see you does not use it ?

**Comment by ajeetraina** [comment]
In laymen language, Docker compose helps you to build and run the microservices and provide a means to let them talk to each other in the standalone or the cluster environment. It is a YAML file where you can define services along with specification and just one liner command to bring the services up.

**Comment by dlgiang** [comment]
Thank you. Just because i see you already use docker swarm in the instruction.
